<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-M932U75" failures="1" tests="2" name="Mytest" time="48.257" errors="0" timestamp="2023-04-06T16:21:29 IST">
  <testcase classname="com.raffolux.testcases.End_2_End_Testcases_Test" name="Verify_By_Clicking_Raffolux_Link" time="27.631"/>
  <testcase classname="com.raffolux.testcases.End_2_End_Testcases_Test" name="Verify_Create_Account_Test" time="19.39">
    <failure type="java.lang.AssertionError" message="User successfuilly signed_Up to the application expected [https://sandbox.raffolux.com/signup/] but found [https://sandbox.raffolux.com/]">
      <![CDATA[java.lang.AssertionError: User successfuilly signed_Up to the application expected [https://sandbox.raffolux.com/signup/] but found [https://sandbox.raffolux.com/]
at com.raffolux.testcases.End_2_End_Testcases_Test.Verify_Create_Account_Test(End_2_End_Testcases_Test.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Verify_Create_Account_Test -->
</testsuite> <!-- Mytest -->
